### ISSUE TITLE
-dtypecheck debug flag causes Sexp error

### ISSUE THREAD

**Issue by dzagieboylo** [dz333/secverilog#5]
When running any test with the -dtypecheck flag
(e.g., from the "test" directory `../bin/iverilog -dtypecheck -F deptype-example.fun -l deptype-example.lattice -z deptype-example.v`)

You get an error printing a naked atom:

```
debug: Enable type-checking debug
about to typecheck
Module::check deptype
Port::check clk(clk)
Port::check timer(timer)
Port::check data(data)
Port::check out(out)
typechecking localparams
typecheck_localparams for deptype
typechecking wires
PWire::check wire /*implicit*/ input <no_type> port<scalar> clk;
updating typeEnv for clk with sectype: Error with sexpifying: SexpPrinter: cannot print naked atom!
done with typecheck
```

**Comment by charles-rs** [comment]
https://github.com/dz333/secverilog/commit/0daaf9b534624255e9bd65acc9be5efda5e5bedc

i was making temporary SexpPrinter objects to generate the strings for sectypes to put into normal ostreams. These need to allow naked atoms. I believe this is fixed now
